# Generated by Django 5.0.6 on 2024-06-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type_item', models.CharField(choices=[('APARTAMENTO', 'APARTAMENTO'), ('KITNET', 'KITNET'), ('CASA', 'CASA')], max_length=100)),
                ('address', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_locate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Immobile',
                'verbose_name_plural': 'Properties',
                'ordering': ['-id'],
            },
        ),
    ]
