# Generated by Django 5.0.6 on 2024-06-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiles', '0002_immobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmobileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Images')),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobile_images', to='immobiles.immobile')),
            ],
        ),
    ]
