# Generated by Django 5.0.6 on 2024-06-26 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiles', '0003_immobileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_start', models.DateTimeField(verbose_name='Start')),
                ('dt_end', models.DateTimeField(verbose_name='End')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immobiles.customer')),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_location', to='immobiles.immobile')),
            ],
            options={
                'verbose_name': 'Register Location',
                'verbose_name_plural': 'Register Locations',
                'ordering': ['-id'],
            },
        ),
    ]
