# Generated by Django 5.0.6 on 2024-07-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobiles', '0005_customer_created_on_customer_update_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
